### ISSUE TITLE
Repository License?

### ISSUE THREAD

**Issue by pyrrho** [thomaslevesque/GenerateCSharpErrors#2]
First I'd like to thank you for putting together this script and repository. It's already been helpful in some explorations I've been doing to update a legacy build system implemented in a series of Azure pipelines.

I'm curious if you'd be willing to apply an open-source license to the repository, though. I'm going to try to document the updated build system as completely as possible, and I'm considering implementing something like this as part of the document generation. I'd like to build on what you have here, but because my work is being done in a commercial context and on a different platform I don't feel comfortable pulling in this code without permission.

Thanks again!

**Comment by thomaslevesque** [comment]
Hi @pyrrho,

Thanks for your interest in this repo. I never thought about applying a license to it, because it was just a toy project, but I realize now that I should have. You can use the code, of course. I'll add the MIT license, which should be permissive enough.
