### ISSUE TITLE
I think this tool will miss doc links to articles with multiple errors

### ISSUE THREAD

**Issue by BillWagner** [thomaslevesque/GenerateCSharpErrors#4]
First off, thanks for writing this. It's super useful! 

Over time, I'm working on different ways to minimize the number of C# compiler messages not documented. See dotnet/docs#24002.

As I work on those areas, I'm starting to create single articles that provide guidance for a related set of errors / warnings.  You can see two examples here:

- [Nullable warnings](https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-messages/nullable-warnings)
- [Warning waves](https://docs.microsoft.com/dotnet/csharp/language-reference/compiler-messages/warning-waves)

It appears that `GetDocLink` will miss any errors and warnings in those two articles (and others I'll be writing going forward).

I can submit a PR if you want.

**Comment by thomaslevesque** [comment]
Hi @BillWagner,

Thanks for reporting this!

I see that @peteraritchie already submitted a PR, which looks good to me in the current state of the docs, but maybe you had a more robust approach in mind?

**Comment by BillWagner** [comment]
Hi @thomaslevesque 

I looked at the PR, and it looks great.

I may try a fork to make sure that all the `displayName` keys match the `f1_keyword` tags in the source. I think that would be much better to run on a local copy of the repo rather than grabbing the source across the web. I always have a local copy, and that will help me. I'll use different command line options, and make the default off.

Once I get it working, I'll make a PR, if you want to accept it. If that's not useful, that's fine too.

**Comment by thomaslevesque** [comment]
> I think that would be much better to run on a local copy of the repo rather than grabbing the source across the web

Definitely. I'm looking forward to your PR!
